"""
Liouville-space 2D spectroscopy solver, version 6.

V6 additions
------------
1. Configurable initial density matrix::

       system.feed_model(
           H_raw,
           mu_opt,
           interaction_type="dipole",
           initial_density_matrix=rho0,
           density_matrix_basis="site",
       )

   It can also be changed after ``feed_model``::

       system.set_initial_density_matrix(rho0, basis="eigen")
       system.clear_initial_density_matrix()  # restore thermal/default rho

2. UFSS pathway generation and translation::

       pathways = system.configure_standard_2d_pathways_with_ufss(
           arrival_times=[0, 100, 200, 300]
       )

   Existing UFSS DiagramGenerator output can be activated directly::

       pathways = system.set_pathways_from_ufss(
           ufss_diagrams,
           component="rephasing",
       )

   The frequency solver is impulsive and third order. By default, translated
   diagrams must contain three interactions in pulse order (0, 1, 2).

3. Individual pathway spectra::

       pathway_spectra = system.generate_2D_pathways(
           w_list,
           tau2=3,
           k_array=k_array,
       )

4. Selective plotting::

       plotter = SpectroscopyPlotter(w_list)
       plotter.plot_rephasing(spectra, component="real")
       plotter.plot_unrephasing(spectra, component="imag")
       plotter.plot_pathway(pathway_spectra, "R1", component="abs")
       plotter.plot_pathways(pathway_spectra, component="real")

The legacy V5 calls remain available, including ``generate_2D_spectra`` and
``SpectroscopyPlotter.plot_spectrum``.
"""

from collections import OrderedDict
from concurrent.futures import ProcessPoolExecutor
from contextlib import nullcontext
from dataclasses import dataclass
import math
import os
import time
import warnings

import matplotlib.pyplot as plt
import numpy as np
from scipy import sparse as sp
from scipy.sparse.linalg import expm, expm_multiply, factorized, gmres
from joblib import Parallel, delayed

try:
    from threadpoolctl import threadpool_limits
except ImportError:
    threadpool_limits = None


_PROCESS_SOLVER = None


def _init_process_solver(solver):
    """Store one solver copy per process worker."""
    global _PROCESS_SOLVER
    _PROCESS_SOLVER = solver


def _calc_w3_block_process(block, w_list, tau2, integration_factor, spectrum_components):
    """ProcessPool worker entry point using the process-local solver."""
    if _PROCESS_SOLVER is None:
        raise RuntimeError("Process worker was not initialized with a solver.")
    return _PROCESS_SOLVER._calc_w3_block(
        block, w_list, tau2, integration_factor, spectrum_components
    )


def _calc_w3_block_joblib(solver, block, w_list, tau2, integration_factor, spectrum_components):
    """Joblib worker entry point for process-style backends."""
    return solver._calc_w3_block(
        block, w_list, tau2, integration_factor, spectrum_components
    )


@dataclass(frozen=True)
class FrequencyPathway:
    """
    Frequency-domain representation of one UFSS density-matrix diagram.

    Parameters
    ----------
    name : str
        Public pathway label, for example ``R1``.
    interactions : tuple of str
        Ordered UFSS interaction labels (Ku, Kd, Bu, Bd).
    pulse_indices : tuple of int
        UFSS pulse index associated with each interaction.
    component : str
        Spectrum group, normally ``"rephasing"`` or ``"unrephasing"``.
    amplitude : complex
        Additional user-supplied pathway amplitude. The bra-side commutator
        sign is applied automatically by the solver.
    """

    name: str
    interactions: tuple
    pulse_indices: tuple = ()
    component: str = "custom"
    amplitude: complex = 1.0

    def __post_init__(self):
        interactions = tuple(str(item) for item in self.interactions)
        pulse_indices = tuple(int(item) for item in self.pulse_indices)
        component = str(self.component).lower().replace("-", "")
        if component in {"nonrephasing", "nonrephase"}:
            component = "unrephasing"
        valid = {"Ku", "Kd", "Bu", "Bd"}
        unknown = [item for item in interactions if item not in valid]
        if unknown:
            raise ValueError(
                f"Unknown UFSS interaction label(s): {unknown}. "
                "Expected Ku, Kd, Bu, or Bd."
            )
        if pulse_indices and len(pulse_indices) != len(interactions):
            raise ValueError(
                "pulse_indices must be empty or have one entry per interaction."
            )
        object.__setattr__(self, "interactions", interactions)
        object.__setattr__(self, "pulse_indices", pulse_indices)
        object.__setattr__(self, "component", component)
        object.__setattr__(self, "amplitude", complex(self.amplitude))

    @property
    def bra_sign(self):
        """Commutator sign generated by bra-side interactions."""
        return -1 if sum(item.startswith("B") for item in self.interactions) % 2 else 1

    @property
    def coefficient(self):
        """Total relative pathway coefficient, excluding the common ``-1j``."""
        return self.amplitude * self.bra_sign
###################################################################################
#################             Author: Mathieu Desmarais            ################
#################                Date: 25-06-2026                  ################
#################           2D spectroscopy solver - V6            ################
###################################################################################


class LiouvilleSpectroscopySolver:
    def __init__(self, params):
        """
        Universal Liouville-space solver for 2D spectroscopy.

        Parameters
        ----------
        params : dict
            Expected keys include:
            - Eta: spectral broadening
            - T: temperature
            - mu: chemical potential
            - cache_resolvents: whether sparse LU factorizations are cached
            - max_resolvent_cache: optional maximum number of cached factorizations
        """
        self.params = params
        self.eta = params.get("Eta", 0.05)
        self.T = params.get("T", 0.01)
        self.rwa_tol = params.get("rwa_tol", 1e-6)
        self.cache_resolvents = params.get("cache_resolvents", True)
        self.max_resolvent_cache = params.get("max_resolvent_cache", None)
        self.backend = params.get("backend", "auto")
        self.dense_liouville_cutoff = params.get("dense_liouville_cutoff", 512)
        self.sparse_solver = params.get("sparse_solver", "auto")
        self.sparse_gmres_rtol = params.get("sparse_gmres_rtol", 1e-8)
        self.sparse_gmres_atol = params.get("sparse_gmres_atol", 0.0)
        self.sparse_gmres_maxiter = params.get("sparse_gmres_maxiter", None)
        self.cache_sparse_tau2 = params.get("cache_sparse_tau2", False)
        self.parallel_backend = params.get("parallel_backend", "threading")
        self.parallel_block_size = params.get("parallel_block_size", None)
        self.blas_threads = params.get("blas_threads", None)
        self.n_jobs = params.get("n_jobs", -1)
        self.spectrum_components = self._normalize_spectrum_components(
            params.get("spectrum_components", "both")
        )
        self.density_matrix_tolerance = params.get(
            "density_matrix_tolerance", 1e-10
        )
        self._active_backend = None
        self._sparse_direct_failed = False

        self.H_eigen = None
        self.energies = None
        self.eigenvectors = None
        self.J_plus = None
        self.J_minus = None

        self.c_ops = []
        self.c_ops_eigen = []

        self.dim = None
        self.N_k = None

        self._I_d_sp = None
        self._I_super_sp = None
        self._trace_vec = None
        self._rho_eq = None
        self._initial_density_matrix_eigen = None
        self._pending_initial_density_matrix = params.get(
            "initial_density_matrix", params.get("rho0", None)
        )
        self._pending_density_matrix_basis = params.get(
            "density_matrix_basis", "site"
        )
        self._JL_plus = []
        self._JR_plus = []
        self._JL_minus = []
        self._JR_minus = []
        self._JL_out = []
        self._L_eff_sp = []
        self._resolvent_cache = OrderedDict()
        self._sparse_tau2_cache = OrderedDict()
        self._I_super_dense = None
        self._rho_eq_dense = None
        self._trace_vec_dense = None
        self._JL_plus_dense = None
        self._JR_plus_dense = None
        self._JL_minus_dense = None
        self._JR_minus_dense = None
        self._JL_out_dense = None
        self._L_eff_dense = None
        self._dense_resolvent_cache = OrderedDict()
        self._dense_tau2_cache = OrderedDict()
        self.pathways = self._default_frequency_pathways()

    def _normalize_spectrum_components(self, spectrum_components):
        """Normalize the requested 2D spectrum components."""
        if spectrum_components is None:
            spectrum_components = getattr(self, "spectrum_components", "both")
        spectrum_components = str(spectrum_components).lower()
        valid = {"both", "rephasing", "unrephasing"}
        if spectrum_components not in valid:
            raise ValueError(
                "spectrum_components must be one of: "
                "'both', 'rephasing', or 'unrephasing'"
            )
        return spectrum_components

    def _wants_rephasing(self, spectrum_components):
        return spectrum_components in {"both", "rephasing"}

    def _wants_unrephasing(self, spectrum_components):
        return spectrum_components in {"both", "unrephasing"}

    def _format_spectra_result(self, S3_reph, S3_unreph, spectrum_components):
        """Build the public spectra dictionary for the requested components."""
        result = {}
        if self._wants_rephasing(spectrum_components):
            result["rephasing"] = S3_reph
        if self._wants_unrephasing(spectrum_components):
            result["unrephasing"] = S3_unreph
        if spectrum_components == "both":
            result["absorptive"] = S3_reph + S3_unreph
        return result

    # ========================================================================
    # PATHWAY DEFINITIONS AND UFSS TRANSLATION
    # ========================================================================

    def _default_frequency_pathways(self):
        """
        Return the six impulsive third-order pathways used by the old solver.

        The R labels follow the ordering used by UFSS/QuDPy examples:
        R1=SE, R2=GSB, R3=ESA for rephasing and R4=ESA, R5=SE,
        R6=GSB for unrephasing.
        """
        return [
            FrequencyPathway("R1", ("Bu", "Ku", "Bd"), (0, 1, 2), "rephasing"),
            FrequencyPathway("R2", ("Bu", "Bd", "Ku"), (0, 1, 2), "rephasing"),
            FrequencyPathway("R3", ("Bu", "Ku", "Ku"), (0, 1, 2), "rephasing"),
            FrequencyPathway("R4", ("Ku", "Bu", "Ku"), (0, 1, 2), "unrephasing"),
            FrequencyPathway("R5", ("Ku", "Bu", "Bd"), (0, 1, 2), "unrephasing"),
            FrequencyPathway("R6", ("Ku", "Kd", "Ku"), (0, 1, 2), "unrephasing"),
        ]

    def reset_pathways(self):
        """Restore the six standard third-order pathways."""
        self.pathways = self._default_frequency_pathways()

    def get_pathways(self, component=None):
        """Return configured pathways, optionally filtered by component."""
        if component is None:
            return list(self.pathways)
        component = str(component).lower().replace("-", "")
        if component in {"nonrephasing", "nonrephase"}:
            component = "unrephasing"
        return [pathway for pathway in self.pathways if pathway.component == component]

    def pathway_summary(self, component=None):
        """Return the active pathway definitions in a notebook-friendly form."""
        return [
            {
                "name": pathway.name,
                "component": pathway.component,
                "interactions": pathway.interactions,
                "pulse_indices": pathway.pulse_indices,
                "amplitude": pathway.amplitude,
                "bra_sign": pathway.bra_sign,
                "coefficient": pathway.coefficient,
            }
            for pathway in self.get_pathways(component)
        ]

    def set_pathways(self, pathways):
        """
        Replace the active pathway list.

        Entries may be :class:`FrequencyPathway` objects or dictionaries with
        matching constructor keys.
        """
        normalized = []
        names = set()
        for item in pathways:
            pathway = item if isinstance(item, FrequencyPathway) else FrequencyPathway(**item)
            if len(pathway.interactions) != 3:
                raise ValueError(
                    "The current 2D frequency solver requires exactly three "
                    f"interactions per pathway; {pathway.name!r} has "
                    f"{len(pathway.interactions)}."
                )
            if pathway.name in names:
                raise ValueError(f"Duplicate pathway name: {pathway.name!r}")
            names.add(pathway.name)
            normalized.append(pathway)
        if not normalized:
            raise ValueError("At least one pathway is required.")
        self.pathways = normalized

    def _phase_discrimination_component(self, phase_discrimination):
        """Infer the standard 2D component from a UFSS phase condition."""
        normalized = []
        for item in phase_discrimination:
            if isinstance(item, str):
                normalized.append(item)
            else:
                rotating, counter_rotating = item
                normalized.append(
                    "+" * int(rotating) + "-" * int(counter_rotating)
                )
        normalized = tuple(normalized)
        if normalized == ("-", "+", "+"):
            return "rephasing"
        if normalized == ("+", "-", "+"):
            return "unrephasing"
        return "custom"

    def _make_pathway_names_unique(self, pathways):
        """Return pathways with stable unique names while preserving metadata."""
        unique = []
        counts = {}
        for pathway in pathways:
            base_name = pathway.name
            counts[base_name] = counts.get(base_name, 0) + 1
            name = (
                base_name
                if counts[base_name] == 1
                else f"{base_name}_{counts[base_name]}"
            )
            if name == pathway.name:
                unique.append(pathway)
            else:
                unique.append(
                    FrequencyPathway(
                        name=name,
                        interactions=pathway.interactions,
                        pulse_indices=pathway.pulse_indices,
                        component=pathway.component,
                        amplitude=pathway.amplitude,
                    )
                )
        return unique

    def translate_ufss_diagrams(
        self,
        diagrams,
        component="auto",
        names=None,
        amplitudes=None,
        allow_noncanonical_order=False,
    ):
        """
        Translate UFSS DiagramGenerator output to frequency pathways.

        UFSS diagrams use ordered ``(instruction, pulse_index)`` pairs. This
        translator preserves that ordering and converts the four UFSS
        instructions directly to the corresponding left/right Liouville
        superoperators. The current solver represents the impulsive
        third-order topology, so each diagram must contain three interactions
        ordered by pulses ``(0, 1, 2)``. Other pulse orders are rejected by
        default because the solver's ``omega1`` and ``omega3`` axes would no
        longer correspond unambiguously to the original pulse-delay axes.
        """
        diagrams = list(diagrams)
        if names is None:
            names = [None] * len(diagrams)
        if amplitudes is None:
            amplitudes = [1.0] * len(diagrams)
        if len(names) != len(diagrams) or len(amplitudes) != len(diagrams):
            raise ValueError(
                "names and amplitudes must have one entry per UFSS diagram."
            )

        standard_names = {
            ("Bu", "Ku", "Bd"): ("R1", "rephasing"),
            ("Bu", "Bd", "Ku"): ("R2", "rephasing"),
            ("Bu", "Ku", "Ku"): ("R3", "rephasing"),
            ("Ku", "Bu", "Ku"): ("R4", "unrephasing"),
            ("Ku", "Bu", "Bd"): ("R5", "unrephasing"),
            ("Ku", "Kd", "Ku"): ("R6", "unrephasing"),
        }

        translated = []
        used_names = set()
        requested_component = (
            None if component is None else str(component).lower()
        )
        for index, (diagram, name, amplitude) in enumerate(
            zip(diagrams, names, amplitudes), start=1
        ):
            diagram = tuple(diagram)
            if len(diagram) != 3:
                raise ValueError(
                    "Only third-order UFSS diagrams can currently be mapped "
                    f"onto (omega1, tau2, omega3); diagram {index} contains "
                    f"{len(diagram)} interactions."
                )
            try:
                interactions = tuple(item[0] for item in diagram)
                pulse_indices = tuple(item[1] for item in diagram)
            except (TypeError, IndexError) as exc:
                raise ValueError(
                    "Each UFSS interaction must be an "
                    "(instruction, pulse_index) pair."
                ) from exc
            if pulse_indices != (0, 1, 2):
                message = (
                    f"UFSS diagram {index} has pulse order {pulse_indices}, "
                    "but the current frequency solver maps its propagation "
                    "intervals to the canonical pulse order (0, 1, 2)."
                )
                if not allow_noncanonical_order:
                    raise ValueError(
                        message
                        + " Use non-overlapping, time-ordered pulses, or set "
                        "allow_noncanonical_order=True only if you explicitly "
                        "want omega1/omega3 to describe the first and last "
                        "intervals of this reordered diagram."
                    )
                warnings.warn(
                    message
                    + " omega1/omega3 will describe the first and last "
                    "propagation intervals of the reordered diagram.",
                    RuntimeWarning,
                    stacklevel=2,
                )

            if pulse_indices == (0, 1, 2):
                standard_name, standard_component = standard_names.get(
                    interactions, (None, None)
                )
            else:
                # R1-R6 labels describe the canonical pulse ordering only.
                standard_name, standard_component = (None, None)
            pathway_name = name or standard_name or f"P{index}"
            base_name = pathway_name
            suffix = 2
            while pathway_name in used_names:
                pathway_name = f"{base_name}_{suffix}"
                suffix += 1
            used_names.add(pathway_name)
            pathway_component = (
                standard_component
                if requested_component in {None, "auto"}
                else requested_component
            )
            if pathway_component is None:
                pathway_component = "custom"
            translated.append(
                FrequencyPathway(
                    pathway_name,
                    interactions,
                    pulse_indices,
                    pathway_component,
                    amplitude,
                )
            )
        return translated

    def generate_pathways_with_ufss(
        self,
        phase_discrimination,
        arrival_times,
        component="auto",
        efield_times=None,
        names=None,
        amplitudes=None,
        detection_type="polarization",
        replace=False,
        allow_noncanonical_order=False,
    ):
        """
        Generate diagrams with UFSS and translate them for this solver.

        If ``efield_times`` is omitted, delta-like pulses are used. Finite
        pulse windows may cause UFSS to return reordered interactions. Those
        diagrams are rejected unless ``allow_noncanonical_order=True`` because
        this solver does not perform finite-pulse envelope convolutions.
        """
        try:
            import ufss
        except ImportError as exc:
            raise ImportError(
                "UFSS is required for pathway generation. Install it with "
                "`pip install ufss`."
            ) from exc

        generator = ufss.DiagramGenerator(detection_type=detection_type)
        generator.set_phase_discrimination(phase_discrimination)
        if efield_times is None:
            generator.efield_times = [
                np.array([0.0, 0.0], dtype=float)
                for _ in range(len(phase_discrimination))
            ]
        else:
            generator.efield_times = [
                np.asarray(times, dtype=float) for times in efield_times
            ]

        diagrams = generator.get_diagrams(arrival_times)
        translated_component = component
        if component is None or str(component).lower() == "auto":
            translated_component = self._phase_discrimination_component(
                phase_discrimination
            )
        pathways = self.translate_ufss_diagrams(
            diagrams,
            component=translated_component,
            names=names,
            amplitudes=amplitudes,
            allow_noncanonical_order=allow_noncanonical_order,
        )
        if replace:
            self.set_pathways(pathways)
        return pathways

    def set_pathways_from_ufss(
        self,
        diagrams,
        component="auto",
        names=None,
        amplitudes=None,
        allow_noncanonical_order=False,
    ):
        """Translate UFSS output and immediately make it active."""
        pathways = self.translate_ufss_diagrams(
            diagrams,
            component=component,
            names=names,
            amplitudes=amplitudes,
            allow_noncanonical_order=allow_noncanonical_order,
        )
        self.set_pathways(pathways)
        return pathways

    def configure_standard_2d_pathways_with_ufss(
        self,
        arrival_times,
        efield_times=None,
        allow_noncanonical_order=False,
    ):
        """
        Ask UFSS for both standard third-order 2D phase-matching groups.

        The resulting active list is ordered R1 through R6 when all six
        standard impulsive diagrams are present.
        """
        rephasing = self.generate_pathways_with_ufss(
            [(0, 1), (1, 0), (1, 0)],
            arrival_times,
            component="auto",
            efield_times=efield_times,
            allow_noncanonical_order=allow_noncanonical_order,
        )
        unrephasing = self.generate_pathways_with_ufss(
            [(1, 0), (0, 1), (1, 0)],
            arrival_times,
            component="auto",
            efield_times=efield_times,
            allow_noncanonical_order=allow_noncanonical_order,
        )
        pathways = self._make_pathway_names_unique(
            rephasing + unrephasing
        )
        pathways.sort(
            key=lambda item: (
                0,
                int(item.name[1:]),
            )
            if item.name.startswith("R") and item.name[1:].isdigit()
            else (1, item.name)
        )
        self.set_pathways(pathways)
        return pathways

    def _using_default_pathways(self):
        """Whether optimized hard-coded contractions remain applicable."""
        return self.pathways == self._default_frequency_pathways()

    # ========================================================================
    # Parallelisation method
    # ========================================================================

    def _calc_w3_column(
        self, i, w3, w_list, tau2, integration_factor, spectrum_components
    ):
        """
        Calculate a complete omega column of the 2D spectra for a fixed w3.
        This function is executed by an independent worker.
        """
        n_w = len(w_list)
        col_reph = (
            np.zeros(n_w, dtype=np.complex128)
            if self._wants_rephasing(spectrum_components)
            else None
        )
        col_unreph = (
            np.zeros(n_w, dtype=np.complex128)
            if self._wants_unrephasing(spectrum_components)
            else None
        )

        for j, w1 in enumerate(w_list):
            if col_reph is not None:
                vect_reph = self.calc_rephasing(w3, w1, tau2)
                col_reph[j] = np.sum(vect_reph) * integration_factor
            if col_unreph is not None:
                vect_unreph = self.calc_unrephasing(w3, w1, tau2)
                col_unreph[j] = np.sum(vect_unreph) * integration_factor

        return i, col_reph, col_unreph

    def _calc_w3_block(
        self, block, w_list, tau2, integration_factor, spectrum_components
    ):
        """Calculate a block of omega_3 columns."""
        return [
            self._calc_w3_column(
                i, w_list[i], w_list, tau2, integration_factor, spectrum_components
            )
            for i in block
        ]

    def _effective_n_jobs(self, n_jobs):
        """Normalize joblib-style worker counts."""
        cpu_count = os.cpu_count() or 1
        if n_jobs is None:
            return 1
        if n_jobs < 0:
            return max(1, cpu_count + 1 + n_jobs)
        return max(1, int(n_jobs))

    def _make_w3_blocks(self, n_w, n_jobs, block_size):
        """Split omega_3 column indices into backend tasks."""
        if block_size is None:
            block_size = self.parallel_block_size
        if block_size is None:
            target_blocks = max(1, 4 * max(1, n_jobs))
            block_size = max(1, math.ceil(n_w / target_blocks))
        block_size = max(1, int(block_size))
        return [
            list(range(start, min(start + block_size, n_w)))
            for start in range(0, n_w, block_size)
        ]

    def _parallel_context(self, blas_threads):
        """Limit nested BLAS/OpenMP threads while the outer omega loop runs."""
        if blas_threads is None:
            blas_threads = self.blas_threads
        if blas_threads is None or threadpool_limits is None:
            return nullcontext()
        return threadpool_limits(limits=blas_threads)

    def _run_w3_blocks(
        self,
        blocks,
        w_list,
        tau2,
        integration_factor,
        parallel_backend,
        n_jobs,
        spectrum_components,
    ):
        """Run omega_3 blocks using the selected parallel backend."""
        if parallel_backend in {"serial", None} or n_jobs == 1:
            return [
                item
                for block in blocks
                for item in self._calc_w3_block(
                    block, w_list, tau2, integration_factor, spectrum_components
                )
            ]

        if parallel_backend == "threading":
            nested = Parallel(n_jobs=n_jobs, backend="threading")(
                delayed(self._calc_w3_block)(
                    block, w_list, tau2, integration_factor, spectrum_components
                )
                for block in blocks
            )
        elif parallel_backend in {"loky", "multiprocessing"}:
            nested = Parallel(
                n_jobs=n_jobs,
                backend=parallel_backend,
                max_nbytes="10M",
                mmap_mode="r",
            )(
                delayed(_calc_w3_block_joblib)(
                    self,
                    block,
                    w_list,
                    tau2,
                    integration_factor,
                    spectrum_components,
                )
                for block in blocks
            )
        elif parallel_backend in {"process", "processpool"}:
            with ProcessPoolExecutor(
                max_workers=n_jobs,
                initializer=_init_process_solver,
                initargs=(self,),
            ) as pool:
                futures = [
                    pool.submit(
                        _calc_w3_block_process,
                        block,
                        w_list,
                        tau2,
                        integration_factor,
                        spectrum_components,
                    )
                    for block in blocks
                ]
                nested = [future.result() for future in futures]
        else:
            raise ValueError(
                "parallel_backend must be one of: "
                "'serial', 'threading', 'loky', 'multiprocessing', or 'process'"
            )

        return [item for block_result in nested for item in block_result]


    # ========================================================================
    # INPUT NORMALIZATION
    # ========================================================================


    def _clean_gamma(self, gamma):
        """Return a real scalar Lindblad rate."""
        if gamma is None:
            return None

        gamma = np.asarray(gamma).item()
        gamma = np.real_if_close(gamma)
        if np.iscomplexobj(gamma):
            if abs(np.imag(gamma)) > 1e-12:
                raise ValueError(f"Lindblad rates must be real, got {gamma}")
            gamma = np.real(gamma)
        return float(gamma)

    def _as_k_stack(self, array, name):
        """
        Normalize a matrix-like object to shape (N_k, d, d).

        Accepted input shapes are:
        - (d, d)
        - (N_k, d, d)
        """
        array = np.asarray(array, dtype=np.complex128)

        if array.ndim == 2:
            array = array[np.newaxis, :, :]
        elif array.ndim != 3:
            raise ValueError(
                f"{name} must have shape (d, d) or (N_k, d, d); got {array.shape}"
            )

        if array.shape[1] != array.shape[2]:
            raise ValueError(f"{name} must contain square matrices; got {array.shape}")

        return array

    def _broadcast_stack(self, array, name, N_k, dim):
        """Broadcast a single-k matrix stack and validate all dimensions."""
        if array.shape[1:] != (dim, dim):
            raise ValueError(
                f"{name} has matrix shape {array.shape[1:]}, expected {(dim, dim)}"
            )

        if array.shape[0] == N_k:
            return array

        if array.shape[0] == 1 and N_k > 1:
            return np.repeat(array, N_k, axis=0)

        raise ValueError(f"{name} has N_k={array.shape[0]}, expected {N_k}")

    def _split_c_ops(self, c_ops_raw):
        """
        Normalize collapse operators without deciding the final N_k yet.

        Each item can be either:
        - C
        - (C, gamma)
        """
        if c_ops_raw is None:
            return []

        c_ops_prepared = []
        for idx, item in enumerate(c_ops_raw):
            if isinstance(item, tuple) and len(item) == 2:
                C_raw, gamma = item
            else:
                C_raw, gamma = item, None

            C_raw = self._as_k_stack(C_raw, f"c_ops_raw[{idx}]")
            c_ops_prepared.append((C_raw, self._clean_gamma(gamma)))

        return c_ops_prepared

    def _prepare_model_inputs(self, H_model, interaction_op_array, c_ops_raw):
        """Validate and broadcast all model inputs to a common shape."""
        H_model = self._as_k_stack(H_model, "H_model")
        interaction_op_array = self._as_k_stack(
            interaction_op_array, "interaction_op_array"
        )
        c_ops_prepared = self._split_c_ops(c_ops_raw)

        dim = H_model.shape[1]
        candidate_N_k = [H_model.shape[0], interaction_op_array.shape[0]]
        candidate_N_k.extend(C_raw.shape[0] for C_raw, _ in c_ops_prepared)
        N_k = max(candidate_N_k)

        H_model = self._broadcast_stack(H_model, "H_model", N_k, dim)
        interaction_op_array = self._broadcast_stack(
            interaction_op_array, "interaction_op_array", N_k, dim
        )

        c_ops_broadcasted = []
        for idx, (C_raw, gamma) in enumerate(c_ops_prepared):
            C_raw = self._broadcast_stack(C_raw, f"c_ops_raw[{idx}]", N_k, dim)
            c_ops_broadcasted.append((C_raw, gamma))

        return H_model, interaction_op_array, c_ops_broadcasted

    # ========================================================================
    # INITIAL DENSITY MATRIX
    # ========================================================================

    def _matrix_stack_to_vectors(self, matrices):
        """Column-vectorize a matrix stack consistently with ``I kron A``."""
        return matrices.transpose(0, 2, 1).reshape(
            self.N_k, self.dim**2, 1
        )

    def _vectors_to_matrix_stack(self, vectors):
        """Inverse of :meth:`_matrix_stack_to_vectors`."""
        return np.asarray(vectors).reshape(
            self.N_k, self.dim, self.dim
        ).transpose(0, 2, 1)

    def set_initial_density_matrix(
        self,
        rho,
        basis="site",
        normalize=True,
        validate=True,
    ):
        """
        Set the initial density matrix used by every response pathway.

        Parameters
        ----------
        rho : array_like
            Shape ``(d, d)`` or ``(N_k, d, d)``. A single matrix is
            broadcast to every k-point.
        basis : {"site", "eigen"}
            Basis of the supplied matrix. Site-basis matrices are transformed
            with the eigenvectors stored by :meth:`feed_model`.
        normalize : bool
            Normalize each k-point to unit trace.
        validate : bool
            Check Hermiticity, unit trace, and positive semidefiniteness.
        """
        if self.N_k is None or self.dim is None:
            raise RuntimeError(
                "Call feed_model() before set_initial_density_matrix(), or "
                "pass initial_density_matrix directly to feed_model()."
            )
        if basis not in {"site", "eigen"}:
            raise ValueError("basis must be either 'site' or 'eigen'")

        rho_stack = self._as_k_stack(rho, "rho")
        rho_stack = self._broadcast_stack(
            rho_stack, "rho", self.N_k, self.dim
        ).copy()

        if basis == "site":
            rho_eigen = np.empty_like(rho_stack)
            for i_k in range(self.N_k):
                U = self.eigenvectors[i_k]
                rho_eigen[i_k] = U.conj().T @ rho_stack[i_k] @ U
        else:
            rho_eigen = rho_stack

        tol = float(self.density_matrix_tolerance)
        for i_k, rho_k in enumerate(rho_eigen):
            if validate and not np.allclose(
                rho_k, rho_k.conj().T, atol=tol, rtol=0
            ):
                raise ValueError(
                    f"rho[{i_k}] is not Hermitian within tolerance {tol}."
                )

            trace = np.trace(rho_k)
            if abs(trace.imag) > tol or trace.real <= tol:
                raise ValueError(
                    f"rho[{i_k}] must have a positive real trace; got {trace}."
                )
            if normalize:
                rho_eigen[i_k] = rho_k / trace.real
            elif validate and not np.isclose(
                trace.real, 1.0, atol=tol, rtol=0
            ):
                raise ValueError(
                    f"rho[{i_k}] has trace {trace.real}; expected 1."
                )

            if validate:
                eigenvalues = np.linalg.eigvalsh(
                    0.5 * (rho_eigen[i_k] + rho_eigen[i_k].conj().T)
                )
                if np.min(eigenvalues) < -tol:
                    raise ValueError(
                        f"rho[{i_k}] is not positive semidefinite; minimum "
                        f"eigenvalue is {np.min(eigenvalues)}."
                    )

        self._initial_density_matrix_eigen = rho_eigen
        self._refresh_initial_state_vectors()

    def clear_initial_density_matrix(self):
        """Return to the default thermal (or T=0 ground-state) density matrix."""
        self._initial_density_matrix_eigen = None
        self._pending_initial_density_matrix = None
        self._refresh_initial_state_vectors()

    def get_initial_density_matrix(self, basis="eigen"):
        """Return the active normalized density matrix as a matrix stack."""
        if self.N_k is None:
            raise RuntimeError("Call feed_model() before requesting rho0.")
        if basis not in {"site", "eigen"}:
            raise ValueError("basis must be either 'site' or 'eigen'")

        matrices = self._vectors_to_matrix_stack(self._get_initial_state())
        if basis == "eigen":
            return matrices.copy()

        rho_site = np.empty_like(matrices)
        for i_k in range(self.N_k):
            U = self.eigenvectors[i_k]
            rho_site[i_k] = U @ matrices[i_k] @ U.conj().T
        return rho_site

    def _get_initial_state(self):
        """Return the configured or default initial state in vectorized form."""
        if self._initial_density_matrix_eigen is None:
            return self._get_thermal_state()
        return self._matrix_stack_to_vectors(
            self._initial_density_matrix_eigen
        )

    def _refresh_initial_state_vectors(self):
        """Update backend-specific rho vectors without rebuilding Liouvillians."""
        if self.N_k is None or self.dim is None:
            return
        rho_vectors = self._get_initial_state()
        if self._active_backend == "dense":
            self._rho_eq_dense = rho_vectors
        elif self._active_backend == "sparse":
            self._rho_eq = rho_vectors.reshape(self.N_k, self.dim**2)

    # ========================================================================
    # MODEL LOADING
    # ========================================================================
    def feed_model(
        self,
        H_model,
        interaction_op_array,
        c_ops_raw=None,
        interaction_type="dipole",
        initial_density_matrix=None,
        density_matrix_basis=None,
    ):
        """
        Load a model in the site basis and prepare sparse Liouville operators.

        H_model and interaction_op_array must have shape (d, d) or (N_k, d, d).
        c_ops_raw may contain raw matrices or (matrix, gamma) tuples. If gammas
        are provided here, the dissipation is configured immediately.
        initial_density_matrix may be supplied in the site or eigen basis. If
        omitted, the thermal state determined by T and mu is used.
        """
        H_model, interaction_op_array, c_ops_prepared = self._prepare_model_inputs(
            H_model, interaction_op_array, c_ops_raw
        )

        print(f"--- Model loading (interaction type: {interaction_type}) ---")

        self.N_k, self.dim, _ = H_model.shape
        self.energies = np.zeros((self.N_k, self.dim), dtype=float)
        self.eigenvectors = np.zeros(
            (self.N_k, self.dim, self.dim), dtype=np.complex128
        )
        self.H_eigen = np.zeros(
            (self.N_k, self.dim, self.dim), dtype=np.complex128
        )
        self.J_plus = np.zeros(
            (self.N_k, self.dim, self.dim), dtype=np.complex128
        )
        self.J_minus = np.zeros(
            (self.N_k, self.dim, self.dim), dtype=np.complex128
        )
        self.c_ops_eigen = [
            np.zeros((self.N_k, self.dim, self.dim), dtype=np.complex128)
            for _ in c_ops_prepared
        ]

        for i_k in range(self.N_k):
            evals, evecs = np.linalg.eigh(H_model[i_k])
            evals = np.real_if_close(evals).real

            self.energies[i_k] = evals
            self.eigenvectors[i_k] = evecs
            self.H_eigen[i_k] = np.diag(evals)

            U = evecs
            U_dag = U.conj().T

            O_eigen = U_dag @ interaction_op_array[i_k] @ U

            if interaction_type == "dipole":
                delta_E = evals[:, np.newaxis] - evals[np.newaxis, :]
                self.J_plus[i_k] = np.where(delta_E > self.rwa_tol, O_eigen, 0.0)
                self.J_minus[i_k] = np.where(delta_E < -self.rwa_tol, O_eigen, 0.0)
            elif interaction_type == "current":
                self.J_plus[i_k] = np.tril(O_eigen, k=-1)
                self.J_minus[i_k] = np.triu(O_eigen, k=1)
            else:
                raise ValueError("interaction_type must be 'dipole' or 'current'")

            for idx, (C_raw, _) in enumerate(c_ops_prepared):
                self.c_ops_eigen[idx][i_k] = U_dag @ C_raw[i_k] @ U

        gammas = [gamma for _, gamma in c_ops_prepared]
        if any(gamma is not None for gamma in gammas):
            if any(gamma is None for gamma in gammas):
                raise ValueError(
                    "Either provide a gamma for every collapse operator or call "
                    "set_dissipation() after feed_model()."
                )
            self.c_ops = [
                (self.c_ops_eigen[idx], gamma) for idx, gamma in enumerate(gammas)
            ]
        else:
            self.c_ops = []

        if initial_density_matrix is None:
            initial_density_matrix = self._pending_initial_density_matrix
        if density_matrix_basis is None:
            density_matrix_basis = self._pending_density_matrix_basis
        self._initial_density_matrix_eigen = None
        if initial_density_matrix is not None:
            self.set_initial_density_matrix(
                initial_density_matrix,
                basis=density_matrix_basis,
            )

        self._build_liouville_backend()
        print("Model transformed to the eigenbasis.")
        print(f"Liouville backend ready: {self._active_backend}.")

    def set_dissipation(self, c_ops_list, basis="eigen"):
        """
        Define Lindblad jump operators.

        Parameters
        ----------
        c_ops_list : list
            List of (matrix_stack, gamma) pairs.
        basis : {"eigen", "site"}
            Use "eigen" when the operators are already projected. Use "site"
            to project them with the eigenvectors stored by feed_model().
        """
        if self.N_k is None or self.dim is None:
            raise RuntimeError("Call feed_model() before set_dissipation().")

        if basis not in {"eigen", "site"}:
            raise ValueError("basis must be either 'eigen' or 'site'")

        c_ops_eigen = []
        c_ops_with_gamma = []

        for idx, item in enumerate(c_ops_list):
            if not (isinstance(item, tuple) and len(item) == 2):
                raise ValueError(
                    "set_dissipation expects a list of (matrix_stack, gamma) pairs."
                )

            C_raw, gamma = item
            gamma = self._clean_gamma(gamma)
            C_raw = self._as_k_stack(C_raw, f"c_ops_list[{idx}]")
            C_raw = self._broadcast_stack(
                C_raw, f"c_ops_list[{idx}]", self.N_k, self.dim
            )

            if basis == "site":
                C_eigen = np.zeros_like(C_raw, dtype=np.complex128)
                for i_k in range(self.N_k):
                    U = self.eigenvectors[i_k]
                    C_eigen[i_k] = U.conj().T @ C_raw[i_k] @ U
            else:
                C_eigen = C_raw

            c_ops_eigen.append(C_eigen)
            c_ops_with_gamma.append((C_eigen, gamma))

        self.c_ops_eigen = c_ops_eigen
        self.c_ops = c_ops_with_gamma
        self._build_liouville_backend()
        print("Dissipation operators updated.")

    # ========================================================================
    # BACKEND SELECTION
    # ========================================================================
    def _select_backend(self):
        """Choose the fastest Liouville backend for the current problem size."""
        if self.backend not in {"auto", "dense", "sparse"}:
            raise ValueError("backend must be 'auto', 'dense', or 'sparse'")

        if self.backend in {"dense", "sparse"}:
            return self.backend

        d2 = self.dim**2
        if d2 <= self.dense_liouville_cutoff:
            return "dense"
        return "sparse"

    def _build_liouville_backend(self):
        """Build the active Liouville backend and clear stale caches."""
        self._active_backend = self._select_backend()
        self._sparse_direct_failed = False
        self._dense_resolvent_cache.clear()
        self._dense_tau2_cache.clear()
        self._resolvent_cache.clear()
        self._sparse_tau2_cache.clear()

        if self._active_backend == "dense":
            self._build_dense_liouville()
        else:
            self._build_sparse_liouville()

    # ========================================================================
    # DENSE VECTORIZED LIOUVILLE ALGEBRA
    # ========================================================================
    def _spre_dense(self, A):
        """Left-acting dense superoperator: I_d kron A."""
        I = np.eye(self.dim, dtype=np.complex128)
        res = np.einsum("ij,nkl->nikjl", I, A)
        return res.reshape(self.N_k, self.dim**2, self.dim**2)

    def _spost_dense(self, A):
        """Right-acting dense superoperator: A.T kron I_d."""
        I = np.eye(self.dim, dtype=np.complex128)
        res = np.einsum("nji,kl->nikjl", A, I)
        return res.reshape(self.N_k, self.dim**2, self.dim**2)

    def _get_lindblad_dense(self, C, gamma):
        """Build one dense Lindblad dissipator for every k-point."""
        C_dag = np.conj(C.transpose(0, 2, 1))
        C_dag_C = C_dag @ C
        return gamma * (
            self._spre_dense(C) @ self._spost_dense(C_dag)
            - 0.5 * self._spre_dense(C_dag_C)
            - 0.5 * self._spost_dense(C_dag_C)
        )

    def _build_dense_liouville(self):
        """Precompute dense batched superoperators and the static Liouvillian."""
        d2 = self.dim**2
        self._I_super_dense = np.eye(d2, dtype=np.complex128)
        self._rho_eq_dense = self._get_initial_state()

        self._JL_plus_dense = self._spre_dense(self.J_plus)
        self._JR_plus_dense = self._spost_dense(self.J_plus)
        self._JL_minus_dense = self._spre_dense(self.J_minus)
        self._JR_minus_dense = self._spost_dense(self.J_minus)
        self._JL_out_dense = self._spre_dense(self.J_plus + self.J_minus)

        self._trace_vec_dense = np.zeros((self.N_k, 1, d2), dtype=np.complex128)
        for i in range(self.dim):
            self._trace_vec_dense[:, 0, i * self.dim + i] = 1.0

        self._L_eff_dense = (
            self._spre_dense(self.H_eigen) - self._spost_dense(self.H_eigen)
        ).astype(np.complex128)

        for C_eigen, gamma in self.c_ops:
            self._L_eff_dense += 1j * self._get_lindblad_dense(C_eigen, gamma)

    def _get_dense_resolvent(self, w):
        """
        Return cached dense resolvents for all k-points.

        The Liouvillian does not depend on w in this implementation, so each
        frequency only needs one batched inverse per scan.
        """
        key = float(np.round(w, 12))
        cached = self._dense_resolvent_cache.get(key)
        if cached is not None:
            return cached

   
        A = (w + 1j * self.eta) * self._I_super_dense - self._L_eff_dense
        G = np.linalg.inv(A)
      

        self._dense_resolvent_cache[key] = G
        self._dense_resolvent_cache.move_to_end(key)
        if (
            self.max_resolvent_cache is not None
            and len(self._dense_resolvent_cache) > self.max_resolvent_cache
        ):
            self._dense_resolvent_cache.popitem(last=False)
        return G

    def _get_dense_tau2_propagator(self, tau2):
        """Return cached dense G2 = exp(-i L tau2) for all k-points."""
        key = float(np.round(tau2, 12))
        cached = self._dense_tau2_cache.get(key)
        if cached is not None:
            return cached

    
        evals, evecs = np.linalg.eig(-1j * self._L_eff_dense * tau2)
        G2 = (evecs * np.exp(evals)[:, np.newaxis, :]) @ np.linalg.inv(evecs)
      

        self._dense_tau2_cache[key] = G2
        return G2

    def _calc_rephasing_dense(self, w3, w1, tau2):
        """Compute rephasing diagrams with the dense batched backend."""
      

        G1 = self._get_dense_resolvent(w1)
        G2 = self._get_dense_tau2_propagator(tau2)
        G3 = self._get_dense_resolvent(w3)
        rho = self._rho_eq_dense

        path_gsb = G3 @ (
            self._JL_plus_dense
            @ (G2 @ (self._JR_plus_dense @ (G1 @ (self._JR_minus_dense @ rho))))
        )
        path_se = G3 @ (
            self._JR_plus_dense
            @ (G2 @ (self._JL_plus_dense @ (G1 @ (self._JR_minus_dense @ rho))))
        )
        path_esa = G3 @ (
            self._JL_plus_dense
            @ (G2 @ (self._JL_plus_dense @ (G1 @ (self._JR_minus_dense @ rho))))
        )

        tr_gsb = (self._trace_vec_dense @ (self._JL_out_dense @ path_gsb)).reshape(-1)
        tr_se = (self._trace_vec_dense @ (self._JL_out_dense @ path_se)).reshape(-1)
        tr_esa = (self._trace_vec_dense @ (self._JL_out_dense @ path_esa)).reshape(-1)

       
        return -1j * (tr_gsb + tr_se - tr_esa)

    def _calc_unrephasing_dense(self, w3, w1, tau2):
        """Compute non-rephasing diagrams with the dense batched backend."""
    

        G1 = self._get_dense_resolvent(w1)
        G2 = self._get_dense_tau2_propagator(tau2)
        G3 = self._get_dense_resolvent(w3)
        rho = self._rho_eq_dense

        path_gsb = G3 @ (
            self._JL_plus_dense
            @ (G2 @ (self._JL_minus_dense @ (G1 @ (self._JL_plus_dense @ rho))))
        )
        path_se = G3 @ (
            self._JR_plus_dense
            @ (G2 @ (self._JR_minus_dense @ (G1 @ (self._JL_plus_dense @ rho))))
        )
        path_esa = G3 @ (
            self._JL_plus_dense
            @ (G2 @ (self._JR_minus_dense @ (G1 @ (self._JL_plus_dense @ rho))))
        )

        tr_gsb = (self._trace_vec_dense @ (self._JL_out_dense @ path_gsb)).reshape(-1)
        tr_se = (self._trace_vec_dense @ (self._JL_out_dense @ path_se)).reshape(-1)
        tr_esa = (self._trace_vec_dense @ (self._JL_out_dense @ path_esa)).reshape(-1)

       
        return -1j * (tr_gsb + tr_se - tr_esa)

    def _precompute_rephasing_dense_rhs(self, w_list, G_list, G2):
        """Precompute dense rephasing RHS vectors that only depend on w1."""
        n_w = len(w_list)
        d2 = self.dim**2
        rhs = np.empty((3, n_w, self.N_k, d2, 1), dtype=np.complex128)
        source = self._JR_minus_dense @ self._rho_eq_dense

        for j, G1 in enumerate(G_list):
            v1 = G1 @ source

            mid_gsb = G2 @ (self._JR_plus_dense @ v1)
            rhs[0, j] = self._JL_plus_dense @ mid_gsb

            mid_se_esa = G2 @ (self._JL_plus_dense @ v1)
            rhs[1, j] = self._JR_plus_dense @ mid_se_esa
            rhs[2, j] = self._JL_plus_dense @ mid_se_esa

        return rhs

    def _precompute_unrephasing_dense_rhs(self, w_list, G_list, G2):
        """Precompute dense non-rephasing RHS vectors that only depend on w1."""
        n_w = len(w_list)
        d2 = self.dim**2
        rhs = np.empty((3, n_w, self.N_k, d2, 1), dtype=np.complex128)
        source = self._JL_plus_dense @ self._rho_eq_dense

        for j, G1 in enumerate(G_list):
            v1 = G1 @ source

            mid_gsb = G2 @ (self._JL_minus_dense @ v1)
            rhs[0, j] = self._JL_plus_dense @ mid_gsb

            mid_se_esa = G2 @ (self._JR_minus_dense @ v1)
            rhs[1, j] = self._JR_plus_dense @ mid_se_esa
            rhs[2, j] = self._JL_plus_dense @ mid_se_esa

        return rhs

    def _scan_dense_w3_block(self, block, G_list, rhs, integration_factor):
        """Apply one block of precomputed w3 resolvents to immutable RHS data."""
        n_w = len(G_list)
        trace_vec = self._trace_vec_dense[np.newaxis, np.newaxis, ...]
        output_op = self._JL_out_dense[np.newaxis, np.newaxis, ...]
        columns = []

        for i in block:
            G3 = G_list[i]
            paths = G3[np.newaxis, np.newaxis, ...] @ rhs
            traces = (trace_vec @ (output_op @ paths)).reshape(3, n_w, self.N_k)
            column = (
                -1j
                * np.sum(traces[0] + traces[1] - traces[2], axis=1)
                * integration_factor
            )
            columns.append((i, column))

        return columns

    def _scan_dense_component_from_rhs(
        self,
        G_list,
        rhs,
        integration_factor,
        parallel_backend="serial",
        n_jobs=1,
        block_size=None,
    ):
        """Apply every w3 resolvent to precomputed RHS vectors."""
        n_w = len(G_list)
        spectrum = np.empty((n_w, n_w), dtype=np.complex128)
        blocks = self._make_w3_blocks(n_w, n_jobs, block_size)

        if parallel_backend == "threading" and n_jobs > 1:
            nested = Parallel(n_jobs=n_jobs, backend="threading")(
                delayed(self._scan_dense_w3_block)(
                    block, G_list, rhs, integration_factor
                )
                for block in blocks
            )
            columns = [item for block_result in nested for item in block_result]
        else:
            columns = [
                item
                for block in blocks
                for item in self._scan_dense_w3_block(
                    block, G_list, rhs, integration_factor
                )
            ]

        for i, column in columns:
            spectrum[:, i] = column

        return spectrum

    def _generate_2D_spectra_dense(
        self,
        w_list,
        tau2,
        integration_factor,
        spectrum_components,
        parallel_backend="serial",
        n_jobs=1,
        block_size=None,
    ):
        """Optimized dense 2D scan that reuses all w1-dependent RHS vectors."""
        G_list = [self._get_dense_resolvent(w) for w in w_list]
        G2 = self._get_dense_tau2_propagator(tau2)

        S3_reph = None
        S3_unreph = None

        if self._wants_rephasing(spectrum_components):
            rhs_reph = self._precompute_rephasing_dense_rhs(w_list, G_list, G2)
            S3_reph = self._scan_dense_component_from_rhs(
                G_list,
                rhs_reph,
                integration_factor,
                parallel_backend,
                n_jobs,
                block_size,
            )

        if self._wants_unrephasing(spectrum_components):
            rhs_unreph = self._precompute_unrephasing_dense_rhs(w_list, G_list, G2)
            S3_unreph = self._scan_dense_component_from_rhs(
                G_list,
                rhs_unreph,
                integration_factor,
                parallel_backend,
                n_jobs,
                block_size,
            )

        return self._format_spectra_result(
            S3_reph, S3_unreph, spectrum_components
        )
    # ========================================================================
    # SPARSE LIOUVILLE ALGEBRA
    # ========================================================================
    def _spre_sp(self, A):
        """Left-acting superoperator: I_d kron A."""
        return sp.kron(self._I_d_sp, A, format="csr")

    def _spost_sp(self, A):
        """Right-acting superoperator: A.T kron I_d."""
        return sp.kron(A.T, self._I_d_sp, format="csr")

    def _get_lindblad_sp(self, C, gamma):
        """Build one sparse Lindblad dissipator in Liouville space."""
        C_dag = C.getH()
        C_dag_C = C_dag @ C
        return gamma * (
            self._spre_sp(C) @ self._spost_sp(C_dag)
            - 0.5 * self._spre_sp(C_dag_C)
            - 0.5 * self._spost_sp(C_dag_C)
        )

    def _build_sparse_liouville(self):
        """Precompute sparse superoperators used by the response functions."""
        if self.N_k is None or self.dim is None:
            return

        d2 = self.dim**2
        self._I_d_sp = sp.identity(self.dim, dtype=np.complex128, format="csr")
        self._I_super_sp = sp.identity(d2, dtype=np.complex128, format="csr")

        self._trace_vec = np.zeros(d2, dtype=np.complex128)
        for i in range(self.dim):
            self._trace_vec[i * self.dim + i] = 1.0

        self._rho_eq = self._get_initial_state().reshape(self.N_k, d2)

        self._JL_plus = []
        self._JR_plus = []
        self._JL_minus = []
        self._JR_minus = []
        self._JL_out = []
        self._L_eff_sp = []

        for i_k in range(self.N_k):
            H_k = sp.diags(
                self.energies[i_k], offsets=0, dtype=np.complex128, format="csr"
            )
            J_plus_k = sp.csr_matrix(self.J_plus[i_k])
            J_minus_k = sp.csr_matrix(self.J_minus[i_k])

            self._JL_plus.append(self._spre_sp(J_plus_k))
            self._JR_plus.append(self._spost_sp(J_plus_k))
            self._JL_minus.append(self._spre_sp(J_minus_k))
            self._JR_minus.append(self._spost_sp(J_minus_k))
            self._JL_out.append(self._spre_sp(J_plus_k + J_minus_k))

            L = (self._spre_sp(H_k) - self._spost_sp(H_k)).astype(np.complex128)

            for C_stack, gamma in self.c_ops:
                C_k = sp.csr_matrix(C_stack[i_k])
                L = L + 1j * self._get_lindblad_sp(C_k, gamma)

            self._L_eff_sp.append(L.tocsr())

        self._resolvent_cache.clear()

    def _solve_resolvent(self, i_k, w, rhs):
        """
        Apply the resolvent without building an explicit inverse matrix.

        This solves:
            ((w + i eta) I - L) x = rhs
        """
        key = (i_k, float(np.round(w, 12)))
        t0 = time.time()

        A = None
        use_direct = self.sparse_solver in {"auto", "direct"} and not self._sparse_direct_failed

        if use_direct:
            solve = self._resolvent_cache.get(key)
            if solve is None:
                try:
                    A = (
                        (w + 1j * self.eta) * self._I_super_sp
                        - self._L_eff_sp[i_k]
                    ).tocsc()
                    solve = factorized(A)
                except MemoryError:
                    if self.sparse_solver == "direct":
                        raise
                    self._sparse_direct_failed = True
                    self._resolvent_cache.clear()
                    solve = None

                if solve is not None and self.cache_resolvents:
                    self._resolvent_cache[key] = solve
                    self._resolvent_cache.move_to_end(key)
                    if (
                        self.max_resolvent_cache is not None
                        and len(self._resolvent_cache) > self.max_resolvent_cache
                    ):
                        self._resolvent_cache.popitem(last=False)

            if solve is not None:
                result = solve(rhs)
                
                return result

        if A is None:
            A = ((w + 1j * self.eta) * self._I_super_sp - self._L_eff_sp[i_k]).tocsr()

        result, info = gmres(
            A,
            rhs,
            rtol=self.sparse_gmres_rtol,
            atol=self.sparse_gmres_atol,
            maxiter=self.sparse_gmres_maxiter,
        )
        if info != 0:
            raise RuntimeError(
                f"GMRES did not converge for k={i_k}, w={w}. info={info}"
            )
       
        return result

    def _propagate_tau2(self, i_k, tau2, rhs):
        """Apply exp(-i L tau2) to a vector using a sparse exponential action."""
        if not self.cache_sparse_tau2:
            return expm_multiply((-1j * tau2) * self._L_eff_sp[i_k], rhs)

        key = (i_k, float(np.round(tau2, 12)))
        G2 = self._sparse_tau2_cache.get(key)
        if G2 is None:
            G2 = expm((-1j * tau2) * self._L_eff_sp[i_k]).tocsr()
            self._sparse_tau2_cache[key] = G2
        return G2 @ rhs

    def _trace_output(self, i_k, response_vec):
        """Apply the output interaction and take the Liouville trace."""
        return self._trace_vec @ (self._JL_out[i_k] @ response_vec)

    def _get_thermal_state(self):
        """Compute the vectorized initial thermal equilibrium state."""
        d = self.dim
        d2 = d**2
        kB = 8.6173e-5
        mu = self.params.get("mu", 0.0)

        if self.T > 0:
            beta = 1.0 / (kB * self.T)
            shifted = self.energies - mu
            shifted = shifted - np.min(shifted, axis=1, keepdims=True)
            weights = np.exp(-beta * shifted)
            rho_diag = weights / np.sum(weights, axis=1, keepdims=True)
        else:
            rho_diag = np.zeros((self.N_k, d), dtype=float)
            rho_diag[:, 0] = 1.0

        rho_vec = np.zeros((self.N_k, d2, 1), dtype=np.complex128)
        for i in range(d):
            rho_vec[:, i * d + i, 0] = rho_diag[:, i]

        return rho_vec

    # ========================================================================
    # RESPONSE FUNCTIONS
    # ========================================================================
    def _resolve_pathway(self, pathway):
        """Resolve a pathway name, dictionary, or FrequencyPathway object."""
        if isinstance(pathway, FrequencyPathway):
            return pathway
        if isinstance(pathway, dict):
            return FrequencyPathway(**pathway)
        if isinstance(pathway, str):
            matches = [item for item in self.pathways if item.name == pathway]
            if not matches:
                available = ", ".join(item.name for item in self.pathways)
                raise KeyError(
                    f"Unknown pathway {pathway!r}. Available pathways: {available}"
                )
            return matches[0]
        raise TypeError(
            "pathway must be a name, dictionary, or FrequencyPathway."
        )

    def _interaction_dense(self, instruction):
        """Return the dense superoperator for one UFSS instruction."""
        return {
            "Ku": self._JL_plus_dense,
            "Kd": self._JL_minus_dense,
            "Bu": self._JR_minus_dense,
            "Bd": self._JR_plus_dense,
        }[instruction]

    def _interaction_sparse(self, i_k, instruction):
        """Return the sparse superoperator for one UFSS instruction."""
        return {
            "Ku": self._JL_plus,
            "Kd": self._JL_minus,
            "Bu": self._JR_minus,
            "Bd": self._JR_plus,
        }[instruction][i_k]

    def _calc_pathway_dense(self, pathway, w3, w1, tau2):
        """Evaluate one translated pathway with the dense backend."""
        G1 = self._get_dense_resolvent(w1)
        G2 = self._get_dense_tau2_propagator(tau2)
        G3 = self._get_dense_resolvent(w3)
        op1, op2, op3 = (
            self._interaction_dense(item) for item in pathway.interactions
        )

        response = op1 @ self._rho_eq_dense
        response = G1 @ response
        response = op2 @ response
        response = G2 @ response
        response = op3 @ response
        response = G3 @ response
        traces = (
            self._trace_vec_dense @ (self._JL_out_dense @ response)
        ).reshape(-1)
        return -1j * pathway.coefficient * traces

    def calc_pathway(self, pathway, w3, w1, tau2):
        """
        Evaluate one named or explicit pathway for every k-point.

        This is the common execution path for built-in and UFSS-generated
        diagrams.
        """
        if self._active_backend is None:
            raise RuntimeError("Call feed_model() before calc_pathway().")
        pathway = self._resolve_pathway(pathway)
        if len(pathway.interactions) != 3:
            raise ValueError(
                "calc_pathway requires three interactions for the "
                "(omega1, tau2, omega3) propagation sequence."
            )

        if self._active_backend == "dense":
            return self._calc_pathway_dense(pathway, w3, w1, tau2)

        response = np.zeros(self.N_k, dtype=np.complex128)
        for i_k in range(self.N_k):
            state = self._interaction_sparse(
                i_k, pathway.interactions[0]
            ) @ self._rho_eq[i_k]
            state = self._solve_resolvent(i_k, w1, state)
            state = self._interaction_sparse(
                i_k, pathway.interactions[1]
            ) @ state
            state = self._propagate_tau2(i_k, tau2, state)
            state = self._interaction_sparse(
                i_k, pathway.interactions[2]
            ) @ state
            state = self._solve_resolvent(i_k, w3, state)
            response[i_k] = (
                -1j
                * pathway.coefficient
                * self._trace_output(i_k, state)
            )
        return response

    def calc_rephasing(self, w3, w1, tau2):
        """Compute rephasing diagrams (-k1, +k2, +k3)."""
        pathways = self.get_pathways("rephasing")
        response = np.zeros(self.N_k, dtype=np.complex128)
        for pathway in pathways:
            response += self.calc_pathway(pathway, w3, w1, tau2)
        return response

    def calc_unrephasing(self, w3, w1, tau2):
        """Compute non-rephasing diagrams (+k1, -k2, +k3)."""
        pathways = self.get_pathways("unrephasing")
        response = np.zeros(self.N_k, dtype=np.complex128)
        for pathway in pathways:
            response += self.calc_pathway(pathway, w3, w1, tau2)
        return response

    def generate_2D_spectra(
        self,
        w_list,
        tau2,
        k_array=None,
        n_jobs=None,
        parallel_backend=None,
        block_size=None,
        blas_threads=None,
        spectrum_components=None,
        verbose=True,
    ):
        """
        Scan the w1/w3 grid and integrate over k.

        Parameters
        ----------
        parallel_backend : {"serial", "threading", "loky", "multiprocessing", "process"}
            Backend used for the omega_3 column loop. "process" uses a
            ProcessPoolExecutor initializer so the solver is copied once per
            worker instead of once per omega block.
        block_size : int or None
            Number of omega_3 columns per submitted task. Larger blocks reduce
            process-backend overhead.
        blas_threads : int or None
            Optional limit for nested BLAS/OpenMP threads during this scan.
        spectrum_components : {"both", "rephasing", "unrephasing"} or None
            Components to calculate. None uses the value configured in params.

        Returns
        -------
        dict
            Complex 2D response matrices for the requested components. The
            absorptive spectrum is returned only when both components are
            requested.
        """
        if n_jobs is None:
            n_jobs = self.n_jobs
        if self.N_k is None:
            raise RuntimeError("Call feed_model() before generate_2D_spectra().")

        spectrum_components = self._normalize_spectrum_components(
            spectrum_components
        )

        self._resolvent_cache.clear()
        self._dense_resolvent_cache.clear()
        self._dense_tau2_cache.clear()

        w_list = np.asarray(w_list, dtype=float)
        n_w = len(w_list)

        if k_array is not None and self.N_k > 1:
            k_array = np.asarray(k_array, dtype=float)
            if len(k_array) != self.N_k:
                raise ValueError(
                    f"k_array has length {len(k_array)}, expected {self.N_k}"
                )
            dk = (k_array[-1] - k_array[0]) / len(k_array)
            integration_factor = dk / (2 * np.pi)
        else:
            integration_factor = 1.0

        if parallel_backend is None:
            parallel_backend = self.parallel_backend
        n_jobs_eff = self._effective_n_jobs(n_jobs)

        if verbose:
            print(
                f"Starting 2D scan on a {n_w}x{n_w} frequency grid "
                f"with Liouville={self._active_backend}, "
                f"components={spectrum_components}, "
                f"parallel={parallel_backend}, n_jobs={n_jobs_eff}."
            )

        if (
            self._active_backend == "dense"
            and self._using_default_pathways()
            and (
            parallel_backend in {"serial", "threading", None} or n_jobs_eff == 1
            )
        ):
            with self._parallel_context(blas_threads):
                return self._generate_2D_spectra_dense(
                    w_list,
                    tau2,
                    integration_factor,
                    spectrum_components,
                    parallel_backend,
                    n_jobs_eff,
                    block_size,
                )

        S3_reph = (
            np.zeros((n_w, n_w), dtype=np.complex128)
            if self._wants_rephasing(spectrum_components)
            else None
        )
        S3_unreph = (
            np.zeros((n_w, n_w), dtype=np.complex128)
            if self._wants_unrephasing(spectrum_components)
            else None
        )

        blocks = self._make_w3_blocks(n_w, n_jobs_eff, block_size)

        if verbose:
            print(f"block_size={len(blocks[0]) if blocks else 0}.")

        with self._parallel_context(blas_threads):
            results = self._run_w3_blocks(
                blocks,
                w_list,
                tau2,
                integration_factor,
                parallel_backend,
                n_jobs_eff,
                spectrum_components,
            )

        for i, col_reph, col_unreph in results:
            if S3_reph is not None:
                S3_reph[:, i] = col_reph
            if S3_unreph is not None:
                S3_unreph[:, i] = col_unreph

        return self._format_spectra_result(
            S3_reph, S3_unreph, spectrum_components
        )

    def generate_2D_pathways(
        self,
        w_list,
        tau2,
        pathways=None,
        k_array=None,
        verbose=True,
    ):
        """
        Generate a separate complex 2D spectrum for each requested pathway.

        Parameters
        ----------
        pathways : sequence or None
            Pathway names/objects to calculate. ``None`` uses every configured
            pathway.

        Returns
        -------
        dict
            Mapping ``pathway_name -> complex spectrum``.
        """
        if self.N_k is None:
            raise RuntimeError("Call feed_model() before generate_2D_pathways().")

        selected = (
            list(self.pathways)
            if pathways is None
            else [self._resolve_pathway(item) for item in pathways]
        )
        if not selected:
            raise ValueError("At least one pathway must be selected.")

        w_list = np.asarray(w_list, dtype=float)
        n_w = len(w_list)
        if k_array is not None and self.N_k > 1:
            k_array = np.asarray(k_array, dtype=float)
            if len(k_array) != self.N_k:
                raise ValueError(
                    f"k_array has length {len(k_array)}, expected {self.N_k}"
                )
            dk = (k_array[-1] - k_array[0]) / len(k_array)
            integration_factor = dk / (2 * np.pi)
        else:
            integration_factor = 1.0

        self._resolvent_cache.clear()
        self._dense_resolvent_cache.clear()
        self._dense_tau2_cache.clear()
        spectra = {
            pathway.name: np.zeros(
                (n_w, n_w), dtype=np.complex128
            )
            for pathway in selected
        }

        if verbose:
            names = ", ".join(pathway.name for pathway in selected)
            print(
                f"Calculating {len(selected)} pathway spectrum/s on a "
                f"{n_w}x{n_w} grid: {names}."
            )

        for i, w3 in enumerate(w_list):
            for j, w1 in enumerate(w_list):
                for pathway in selected:
                    response = self.calc_pathway(pathway, w3, w1, tau2)
                    spectra[pathway.name][j, i] = (
                        np.sum(response) * integration_factor
                    )
        return spectra

    def benchmark_2D_parallel_backends(
        self,
        w_list,
        tau2,
        k_array=None,
        backends=("serial", "threading", "loky", "process"),
        n_jobs_values=(1, 2, 4),
        block_size=None,
        blas_threads=1,
        repeats=1,
        max_w_points=None,
    ):
        """
        Benchmark omega-loop parallel backends for generate_2D_spectra().

        A short unmeasured run warms up numerical libraries. The first serial
        configuration is then used as the numerical reference. Timings report
        the median of all repetitions.
        """
        n_w = len(w_list)
        d = self.dim
        d2 = d**2 if d is not None else None

        print("\n--- 2D parallel benchmark context ---")
        print(f"Liouville backend      : {self._active_backend}")
        print(f"Hilbert dimension      : {d}")
        print(f"Liouville dimension    : {d2}")
        print(f"k-points               : {self.N_k}")
        print(f"omega points           : {n_w}")
        print(f"omega grid             : {n_w} x {n_w} = {n_w**2} omega pairs")
        print(f"tau2                   : {tau2}")
        print(f"Eta                    : {self.eta}")
        print(f"BLAS threads limit     : {blas_threads}")
        print(f"tested backends        : {backends}")
        print(f"tested n_jobs          : {n_jobs_values}")
        print(f"block_size             : {block_size}")
        print(f"repeats                : {repeats}")

        if self._active_backend == "sparse":
            print(f"sparse_solver          : {self.sparse_solver}")
            print(f"cache_resolvents       : {self.cache_resolvents}")
            print(f"cache_sparse_tau2      : {self.cache_sparse_tau2}")
            print(f"gmres rtol             : {self.sparse_gmres_rtol}")
            print(f"gmres maxiter          : {self.sparse_gmres_maxiter}")

        if self._active_backend == "dense":
            print(f"dense_liouville_cutoff : {self.dense_liouville_cutoff}")

        print("-------------------------------------\n")





        w_bench = np.asarray(w_list, dtype=float)
        if max_w_points is not None:
            w_bench = w_bench[: int(max_w_points)]

        warmup_w = w_bench[: min(8, len(w_bench))]
        if len(warmup_w):
            self.generate_2D_spectra(
                warmup_w,
                tau2,
                k_array=k_array,
                n_jobs=1,
                parallel_backend="serial",
                block_size=block_size,
                blas_threads=blas_threads,
                verbose=False,
            )

        reference = None
        reference_time = None
        rows = []

        for backend in backends:
            jobs_to_run = (1,) if backend == "serial" else n_jobs_values
            for n_jobs in jobs_to_run:
                elapsed_values = []
                spectra = None

                for _ in range(max(1, int(repeats))):
                    t0 = time.perf_counter()
                    spectra = self.generate_2D_spectra(
                        w_bench,
                        tau2,
                        k_array=k_array,
                        n_jobs=n_jobs,
                        parallel_backend=backend,
                        block_size=block_size,
                        blas_threads=blas_threads,
                        verbose=False,
                    )
                    elapsed = time.perf_counter() - t0
                    elapsed_values.append(elapsed)

                if reference is None:
                    reference = spectra
                    reference_time = float(np.median(elapsed_values))

                max_abs_diff = float(
                    np.max(
                        np.abs(spectra["absorptive"] - reference["absorptive"])
                    )
                )
                median_elapsed = float(np.median(elapsed_values))
                min_elapsed = float(np.min(elapsed_values))
                max_elapsed = float(np.max(elapsed_values))
                speedup = (
                    reference_time / median_elapsed
                    if median_elapsed > 0
                    else np.inf
                )
                row = {
                    "backend": backend,
                    "n_jobs": self._effective_n_jobs(n_jobs),
                    "block_size": block_size,
                    "elapsed_s": median_elapsed,
                    "elapsed_min_s": min_elapsed,
                    "elapsed_max_s": max_elapsed,
                    "speedup_vs_serial": speedup,
                    "max_abs_diff": max_abs_diff,
                }
                rows.append(row)
                print(
                    f"{backend:>15} n_jobs={row['n_jobs']:<3} "
                    f"median={median_elapsed:8.3f}s "
                    f"range=[{min_elapsed:.3f}, {max_elapsed:.3f}]s "
                    f"speedup={speedup:6.2f}x "
                    f"max_abs_diff={max_abs_diff:.3e}"
                )

        return rows




class SpectroscopyPlotter:
    def __init__(self, w_list):
        self.w_list = np.asarray(w_list, dtype=float)

    def _select_component(self, data, component):
        """Select real, imaginary, or absolute data."""
        component = str(component).lower()
        aliases = {
            "real": "real",
            "re": "real",
            "imag": "imag",
            "imaginary": "imag",
            "im": "imag",
            "abs": "abs",
            "absolute": "abs",
            "magnitude": "abs",
        }
        try:
            component = aliases[component]
        except KeyError as exc:
            raise ValueError(
                "component must be 'real', 'imag', or 'abs'."
            ) from exc
        if component == "real":
            return np.real(data), component
        if component == "imag":
            return np.imag(data), component
        return np.abs(data), component

    def _extract_spectrum(self, spectra, key):
        """Accept either a raw matrix or a spectra dictionary."""
        if isinstance(spectra, dict):
            if key not in spectra:
                raise KeyError(
                    f"Spectrum dictionary does not contain {key!r}."
                )
            return np.asarray(spectra[key])
        return np.asarray(spectra)

    def plot(
        self,
        data,
        component="real",
        title=None,
        levels=60,
        cmap=None,
        figsize=(6, 5),
        ax=None,
        save_path=None,
        show=True,
        colorbar=True,
    ):
        """Plot one complex 2D response component and return ``(fig, ax)``."""
        selected, normalized_component = self._select_component(
            np.asarray(data), component
        )
        if cmap is None:
            cmap = "magma" if normalized_component == "abs" else "RdBu_r"
        if title is None:
            title = normalized_component.capitalize()

        if ax is None:
            fig, ax = plt.subplots(figsize=figsize)
        else:
            fig = ax.figure
        self._plot_subplot(
            ax,
            self.w_list,
            selected,
            levels,
            cmap,
            title,
            xlabel=r"$\omega_1$",
            ylabel=r"$\omega_3$",
            vmin=0 if normalized_component == "abs" else None,
            colorbar=colorbar,
        )
        fig.tight_layout()
        if save_path:
            fig.savefig(save_path, dpi=300, bbox_inches="tight")
        if show:
            plt.show()
        return fig, ax

    def plot_rephasing(self, spectra, component="real", **kwargs):
        """Plot a rephasing matrix or ``spectra['rephasing']``."""
        data = self._extract_spectrum(spectra, "rephasing")
        kwargs.setdefault("title", f"{component.capitalize()} / Rephasing")
        return self.plot(data, component=component, **kwargs)

    def plot_unrephasing(self, spectra, component="real", **kwargs):
        """Plot an unrephasing matrix or ``spectra['unrephasing']``."""
        data = self._extract_spectrum(spectra, "unrephasing")
        kwargs.setdefault("title", f"{component.capitalize()} / Unrephasing")
        return self.plot(data, component=component, **kwargs)

    def plot_nonrephasing(self, spectra, component="real", **kwargs):
        """Alias for :meth:`plot_unrephasing`."""
        return self.plot_unrephasing(
            spectra, component=component, **kwargs
        )

    def plot_absorptive(self, spectra, component="real", **kwargs):
        """Plot an absorptive matrix or ``spectra['absorptive']``."""
        data = self._extract_spectrum(spectra, "absorptive")
        kwargs.setdefault("title", f"{component.capitalize()} / Absorptive")
        return self.plot(data, component=component, **kwargs)

    def plot_pathway(
        self,
        pathway_spectra,
        pathway,
        component="real",
        **kwargs,
    ):
        """Plot one R1/R2/... matrix from ``generate_2D_pathways`` output."""
        if isinstance(pathway_spectra, dict):
            if pathway not in pathway_spectra:
                available = ", ".join(pathway_spectra)
                raise KeyError(
                    f"Unknown pathway {pathway!r}. Available: {available}"
                )
            data = pathway_spectra[pathway]
        else:
            data = pathway_spectra
        kwargs.setdefault(
            "title", f"{component.capitalize()} / Pathway {pathway}"
        )
        return self.plot(data, component=component, **kwargs)

    def plot_pathways(
        self,
        pathway_spectra,
        pathways=None,
        component="real",
        levels=60,
        cmap=None,
        ncols=3,
        figsize=None,
        save_path=None,
        show=True,
    ):
        """Plot several individual pathways in a compact grid."""
        if not isinstance(pathway_spectra, dict):
            raise TypeError("pathway_spectra must be a dictionary.")
        if pathways is None:
            pathways = list(pathway_spectra)
        else:
            pathways = list(pathways)
        if not pathways:
            raise ValueError("At least one pathway must be selected.")

        selected_component = self._select_component(
            np.zeros((1, 1)), component
        )[1]
        if cmap is None:
            cmap = "magma" if selected_component == "abs" else "RdBu_r"
        ncols = max(1, int(ncols))
        nrows = math.ceil(len(pathways) / ncols)
        if figsize is None:
            figsize = (5 * ncols, 4.5 * nrows)
        fig, axes = plt.subplots(
            nrows, ncols, figsize=figsize, squeeze=False
        )

        for ax, pathway in zip(axes.flat, pathways):
            if pathway not in pathway_spectra:
                raise KeyError(f"Unknown pathway {pathway!r}.")
            data, _ = self._select_component(
                pathway_spectra[pathway], component
            )
            self._plot_subplot(
                ax,
                self.w_list,
                data,
                levels,
                cmap,
                f"{component.capitalize()} / {pathway}",
                xlabel=r"$\omega_1$",
                ylabel=r"$\omega_3$",
                vmin=0 if selected_component == "abs" else None,
            )
        for ax in axes.flat[len(pathways):]:
            ax.set_visible(False)

        fig.tight_layout()
        if save_path:
            fig.savefig(save_path, dpi=300, bbox_inches="tight")
        if show:
            plt.show()
        return fig, axes

    def plot_spectrum(
        self,
        S3_rephasing,
        S3_nonrephasing,
        levels=60,
        figsize=(12, 14),
        save_path=None,
        show=True,
    ):
        """
        Display the legacy 3x2 real/imaginary/absolute comparison.
        """
        fig, axes = plt.subplots(3, 2, figsize=figsize)
        w = self.w_list

        self._plot_subplot(
            axes[0, 0],
            w,
            np.real(S3_rephasing),
            levels,
            "RdBu_r",
            r"Real / Rephasing",
            ylabel=r"$\omega_3$",
        )
        self._plot_subplot(
            axes[0, 1],
            w,
            np.real(S3_nonrephasing),
            levels,
            "RdBu_r",
            r"Real / Non-rephasing",
        )

        self._plot_subplot(
            axes[1, 0],
            w,
            np.imag(S3_rephasing),
            levels,
            "RdBu_r",
            r"Imaginary / Rephasing",
            ylabel=r"$\omega_3$",
        )
        self._plot_subplot(
            axes[1, 1],
            w,
            np.imag(S3_nonrephasing),
            levels,
            "RdBu_r",
            r"Imaginary / Non-rephasing",
        )

        self._plot_subplot(
            axes[2, 0],
            w,
            np.abs(S3_rephasing),
            levels,
            "magma",
            r"Absolute / Rephasing",
            xlabel=r"$\omega_1$",
            ylabel=r"$\omega_3$",
            vmin=0,
        )
        self._plot_subplot(
            axes[2, 1],
            w,
            np.abs(S3_nonrephasing),
            levels,
            "magma",
            r"Absolute / Non-rephasing",
            xlabel=r"$\omega_1$",
            vmin=0,
        )

        plt.tight_layout()

        if save_path:
            fig.savefig(save_path, dpi=300, bbox_inches="tight")

        if show:
            plt.show()
        return fig, axes

    def _plot_subplot(
        self,
        ax,
        w,
        data,
        levels,
        cmap,
        title,
        xlabel=None,
        ylabel=None,
        vmin=None,
        colorbar=True,
    ):
        """Plot one contour panel."""
        lim = np.max(np.abs(data))
        if not np.isfinite(lim):
            raise ValueError("Spectrum contains non-finite values.")
        if lim == 0:
            lim = np.finfo(float).eps
        if vmin is None:
            vmin, vmax = -lim, lim
        else:
            vmax = lim

        contour = ax.contourf(w, w, data, levels, cmap=cmap, vmin=vmin, vmax=vmax)
        ax.set_title(title)
        if xlabel:
            ax.set_xlabel(xlabel)
        if ylabel:
            ax.set_ylabel(ylabel)
        if colorbar:
            ax.figure.colorbar(contour, ax=ax)
        return contour
